authTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: user
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: username
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
    - IndexName: userToId
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      Projection:
        NonKeyAttributes:
        - userId
        ProjectionType: INCLUDE
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
recipeTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: recipe
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: userId 
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
ingredientTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ingredient
    AttributeDefinitions:
      - AttributeName: ingredientId
        AttributeType: S
      - AttributeName: name
        AttributeType: S
      - AttributeName: metric
        AttributeType: S
    KeySchema:
      - AttributeName: ingredientId
        KeyType: HASH
      - AttributeName: name
        KeyType: RANGE
      - AttributeName: metric
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1