authTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: user
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: username
        AttributeType: S
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
    GlobalSecondaryIndexes:
    - IndexName: userToId
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      Projection:
        NonKeyAttributes:
        - userId
        ProjectionType: INCLUDE
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
recipeTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: recipe
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: recipeId
        KeyType: HASH
      - AttributeName: userId 
        KeyType: RANGE
    
    GlobalSecondaryIndexes:
    - IndexName: recipeToId
      KeySchema:
      - AttributeName: recipeId
        KeyType: HASH
      - AttributeName: userId
        KeyType: HASH
      Projection:
        NonKeyAttributes:
        - userId
        - steps
        - ingredients
        ProjectionType: INCLUDE
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1