export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const REQUEST_AUTH_TOKEN = "REQUEST_AUTH_TOKEN";
export const INVALID_LOGIN_CRED = "INVALID_LOGIN_CRED";
export const CLEAR_AUTH_ALERT = "CLEAR_AUTH_ALERT";
export const INVALID_TOKEN = "INVALID_TOKEN";