export const UPDATE_INGREDIENTS = 'UPDATE_INGREDIENTS';
export const TOGGLE_ADDDIALOGUE = 'TOGGLE_ADDDIALOGUE';
export const ADD_PANTRY_INGREDIENT = 'ADD_PANTRY_INGREDIENT';
export const TOGGLE_PANTRYERROR = 'TOGGLE_PANTRYERROR';

export const DELETE_PANTRY_INGREDIENT = 'DELETE_PANTRY_INGREDIENT';
export const TOGGLE_DELETE_DISPLAY = 'TOGGLE_DELETE_DISPLAY';
export const TOGGLE_DELETE_ERROR = 'TOGGLE_DELETE_ERROR';

export const TOGGLE_EDITDIALOGUE = 'TOGGLE_EDITDIALOGUE';
export const EDIT_PANTRY_INGREDIENT = 'EDIT_PANTRY_INGREDIENT';
export const FETCH_PANTRY_ERROR = 'FETCH_PANTRY_ERROR';
export const SET_PANTRY = 'SET_PANTRY';
