export const UPDATE_INGREDIENTS = 'UPDATE_INGREDIENTS';
export const TOGGLE_ADDDIALOGUE = 'TOGGLE_ADDDIALOGUE';
export const ADD_PANTRY_INGREDIENT = 'ADD_PANTRY_INGREDIENT';
export const TOGGLE_PANTRYERROR = 'TOGGLE_PANTRYERROR';

