name: Deploy dev branch

on:
  push:
    branches:
      - dev
defaults:
  run:
    working-directory: ./mp-backend

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm build
      run: |
        npm i
        npm ci
        npm run build --if-present
    - name: npm test
      run: npm run test
    - name: npm lint
      run: npm run lint
    - name: serverless deploy
      uses: aaronpanch/action-serverless@v1.0.0
      with:
        args: deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVICE_ROOT: ./mp-backend
